import json
import re

# Read the notebook
with open('project.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Fix TF-IDF Sequential - Better scoring logic
for cell in notebook['cells']:
    if cell.get('id') == 'd9190010':  # TF-IDF Sequential
        cell['source'] = [
            "class SequentialTFIDFSummarizer:\n",
            "    \"\"\"\n",
            "    Sequential TF-IDF based text summarization\n",
            "    Processes entire text in single thread\n",
            "    \"\"\"\n",
            "    \n",
            "    def __init__(self, max_features: int = 5000):\n",
            "        self.vectorizer = TfidfVectorizer(\n",
            "            max_features=max_features,\n",
            "            min_df=1,\n",
            "            max_df=0.9,\n",
            "            lowercase=True,\n",
            "            stop_words='english'\n",
            "        )\n",
            "        self.performance_log = []\n",
            "    \n",
            "    def summarize(self, text: str) -> Tuple[str, Dict]:\n",
            "        \"\"\"\n",
            "        Generate summary using sequential TF-IDF approach\n",
            "        Returns: (summary_text, performance_metrics)\n",
            "        \"\"\"\n",
            "        start_time = time.perf_counter()\n",
            "        start_memory = psutil.Process().memory_info().rss / (1024 ** 2)\n",
            "        tracemalloc.start()\n",
            "        \n",
            "        try:\n",
            "            # Preprocess text\n",
            "            sentences, cleaned_text = preprocess_text(text)\n",
            "            \n",
            "            if len(sentences) < 2:\n",
            "                tracemalloc.stop()\n",
            "                return text, {\n",
            "                    'execution_time': time.perf_counter() - start_time,\n",
            "                    'memory_used_mb': 0,\n",
            "                    'peak_memory_mb': 0,\n",
            "                    'num_sentences': len(sentences),\n",
            "                    'summary_sentences': 1,\n",
            "                    'compression_ratio': 0\n",
            "                }\n",
            "            \n",
            "            # Determine summary length\n",
            "            summary_length = calculate_dynamic_summary_length(len(sentences))\n",
            "            \n",
            "            # Compute TF-IDF scores for each sentence separately\n",
            "            sentence_scores = {}\n",
            "            \n",
            "            try:\n",
            "                # Fit vectorizer on all sentences together\n",
            "                tfidf_matrix = self.vectorizer.fit_transform(sentences)\n",
            "                \n",
            "                # Calculate score for each sentence as sum of TF-IDF values\n",
            "                for idx in range(len(sentences)):\n",
            "                    # Sum of all TF-IDF scores in this sentence\n",
            "                    sentence_scores[idx] = float(tfidf_matrix[idx].sum())\n",
            "                    \n",
            "            except Exception as e:\n",
            "                # Fallback: use sentence position (earlier = more important)\n",
            "                for idx in range(len(sentences)):\n",
            "                    sentence_scores[idx] = len(sentences) - idx\n",
            "            \n",
            "            # Get top sentences by score\n",
            "            if sentence_scores and max(sentence_scores.values()) > 0:\n",
            "                # Sort by score (descending) and take top N\n",
            "                top_indices_scored = sorted(\n",
            "                    sentence_scores.items(),\n",
            "                    key=lambda x: x[1],\n",
            "                    reverse=True\n",
            "                )[:summary_length]\n",
            "                \n",
            "                # Extract indices and sort by original position\n",
            "                top_indices = sorted([idx for idx, _ in top_indices_scored])\n",
            "                \n",
            "                # Build summary\n",
            "                summary = ' '.join([sentences[i] for i in top_indices])\n",
            "            else:\n",
            "                # Fallback: take first N sentences\n",
            "                summary = ' '.join(sentences[:summary_length])\n",
            "            \n",
            "            # Calculate performance metrics\n",
            "            end_time = time.perf_counter()\n",
            "            end_memory = psutil.Process().memory_info().rss / (1024 ** 2)\n",
            "            current, peak = tracemalloc.get_traced_memory()\n",
            "            tracemalloc.stop()\n",
            "            \n",
            "            metrics = {\n",
            "                'execution_time': end_time - start_time,\n",
            "                'memory_used_mb': max(0, end_memory - start_memory),\n",
            "                'peak_memory_mb': peak / (1024 ** 2),\n",
            "                'num_sentences': len(sentences),\n",
            "                'summary_sentences': summary_length,\n",
            "                'compression_ratio': max(0, (1 - len(summary.split()) / max(1, len(text.split()))) * 100)\n",
            "            }\n",
            "            \n",
            "            return summary, metrics\n",
            "            \n",
            "        except Exception as e:\n",
            "            tracemalloc.stop()\n",
            "            summary_length = calculate_dynamic_summary_length(len(sentences)) if sentences else 1\n",
            "            summary = ' '.join(sentences[:summary_length]) if sentences else text\n",
            "            return summary, {\n",
            "                'execution_time': time.perf_counter() - start_time,\n",
            "                'memory_used_mb': 0,\n",
            "                'peak_memory_mb': 0,\n",
            "                'num_sentences': len(sentences),\n",
            "                'summary_sentences': summary_length,\n",
            "                'compression_ratio': max(0, (1 - len(summary.split()) / max(1, len(text.split()))) * 100)\n",
            "            }\n",
            "\n",
            "print(\"SequentialTFIDFSummarizer class defined!\")"
        ]
        print("Fixed TF-IDF Sequential with better scoring")
        break

# Save
with open('project.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("TF-IDF Sequential improved!")
print("Now it will select sentences based on TF-IDF importance, not just first N sentences")
