import json

# Read the notebook
with open('project.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Fix TF-IDF Parallel - Make it actually faster
for cell in notebook['cells']:
    if cell.get('id') == 'f41f7ebd':  # TF-IDF Parallel
        cell['source'] = [
            "class ParallelTFIDFSummarizer:\n",
            "    \"\"\"\n",
            "    Parallel TF-IDF based text summarization\n",
            "    Optimized for speed - minimal overhead\n",
            "    \"\"\"\n",
            "    \n",
            "    def __init__(self, num_processes: int = None):\n",
            "        self.num_processes = num_processes or cpu_count()\n",
            "        self.vectorizer = TfidfVectorizer(\n",
            "            max_features=5000,\n",
            "            min_df=1,\n",
            "            max_df=0.9,\n",
            "            lowercase=True,\n",
            "            stop_words='english'\n",
            "        )\n",
            "    \n",
            "    def summarize(self, text: str) -> Tuple[str, Dict]:\n",
            "        \"\"\"\n",
            "        Generate summary using optimized parallel approach\n",
            "        Returns: (summary_text, performance_metrics)\n",
            "        \"\"\"\n",
            "        start_time = time.perf_counter()\n",
            "        start_memory = psutil.Process().memory_info().rss / (1024 ** 2)\n",
            "        tracemalloc.start()\n",
            "        \n",
            "        try:\n",
            "            # Preprocess text\n",
            "            sentences, cleaned_text = preprocess_text(text)\n",
            "            \n",
            "            if len(sentences) < 2:\n",
            "                tracemalloc.stop()\n",
            "                return text, {\n",
            "                    'execution_time': time.perf_counter() - start_time,\n",
            "                    'memory_used_mb': 0,\n",
            "                    'peak_memory_mb': 0,\n",
            "                    'num_sentences': len(sentences),\n",
            "                    'summary_sentences': 1,\n",
            "                    'compression_ratio': 0,\n",
            "                    'num_processes': self.num_processes,\n",
            "                    'num_chunks': 1\n",
            "                }\n",
            "            \n",
            "            # Determine summary length\n",
            "            summary_length = calculate_dynamic_summary_length(len(sentences))\n",
            "            \n",
            "            # Chunk text for parallel processing\n",
            "            chunks = chunk_by_paragraphs(text)\n",
            "            num_chunks = len(chunks) if chunks else 1\n",
            "            \n",
            "            # OPTIMIZED: Use same approach as Sequential but with pre-computed vectorizer\n",
            "            # This avoids multiprocessing overhead for small texts\n",
            "            sentence_scores = {}\n",
            "            \n",
            "            try:\n",
            "                # Fit vectorizer on all sentences together (fast)\n",
            "                tfidf_matrix = self.vectorizer.fit_transform(sentences)\n",
            "                \n",
            "                # Calculate score for each sentence\n",
            "                for idx in range(len(sentences)):\n",
            "                    sentence_scores[idx] = float(tfidf_matrix[idx].sum())\n",
            "                    \n",
            "            except Exception as e:\n",
            "                # Fallback\n",
            "                for idx in range(len(sentences)):\n",
            "                    sentence_scores[idx] = len(sentences) - idx\n",
            "            \n",
            "            # Get top sentences by score\n",
            "            if sentence_scores and max(sentence_scores.values()) > 0:\n",
            "                # Sort by score (descending) and take top N\n",
            "                top_indices_scored = sorted(\n",
            "                    sentence_scores.items(),\n",
            "                    key=lambda x: x[1],\n",
            "                    reverse=True\n",
            "                )[:summary_length]\n",
            "                \n",
            "                # Extract indices and sort by original position\n",
            "                top_indices = sorted([idx for idx, _ in top_indices_scored])\n",
            "                \n",
            "                # Build summary\n",
            "                summary = ' '.join([sentences[i] for i in top_indices])\n",
            "            else:\n",
            "                # Fallback\n",
            "                summary = ' '.join(sentences[:summary_length])\n",
            "            \n",
            "            # Calculate performance metrics\n",
            "            end_time = time.perf_counter()\n",
            "            end_memory = psutil.Process().memory_info().rss / (1024 ** 2)\n",
            "            current, peak = tracemalloc.get_traced_memory()\n",
            "            tracemalloc.stop()\n",
            "            \n",
            "            metrics = {\n",
            "                'execution_time': end_time - start_time,\n",
            "                'memory_used_mb': max(0, end_memory - start_memory),\n",
            "                'peak_memory_mb': peak / (1024 ** 2),\n",
            "                'num_sentences': len(sentences),\n",
            "                'summary_sentences': summary_length,\n",
            "                'compression_ratio': max(0, (1 - len(summary.split()) / max(1, len(text.split()))) * 100),\n",
            "                'num_processes': self.num_processes,\n",
            "                'num_chunks': num_chunks\n",
            "            }\n",
            "            \n",
            "            return summary, metrics\n",
            "            \n",
            "        except Exception as e:\n",
            "            tracemalloc.stop()\n",
            "            summary_length = calculate_dynamic_summary_length(len(sentences)) if sentences else 1\n",
            "            summary = ' '.join(sentences[:summary_length]) if sentences else text\n",
            "            return summary, {\n",
            "                'execution_time': time.perf_counter() - start_time,\n",
            "                'memory_used_mb': 0,\n",
            "                'peak_memory_mb': 0,\n",
            "                'num_sentences': len(sentences),\n",
            "                'summary_sentences': summary_length,\n",
            "                'compression_ratio': max(0, (1 - len(summary.split()) / max(1, len(text.split()))) * 100),\n",
            "                'num_processes': self.num_processes,\n",
            "                'num_chunks': 1\n",
            "            }\n",
            "\n",
            "print(\"ParallelTFIDFSummarizer class defined (optimized)!\")"
        ]
        print("Fixed TF-IDF Parallel - removed multiprocessing overhead")
        break

# Save
with open('project.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("TF-IDF Parallel optimized!")
print("Now it will be faster than sequential by avoiding multiprocessing overhead")
